platform :ios, '12.0'

target 'AimyboxUI' do
  use_frameworks!

  pod 'AimyboxUI', :path => '../'
  pod 'Aimybox/Core', :path => '../../aimybox-ios-sdk/'
  pod 'Aimybox/Utils', :path => '../../aimybox-ios-sdk/'
  pod 'Aimybox/AimyboxDialogAPI', :path => '../../aimybox-ios-sdk/'
  pod 'Aimybox/SFSpeechToText', :path => '../../aimybox-ios-sdk/'
  pod 'Aimybox/AVTextToSpeech', :path => '../../aimybox-ios-sdk/'

end
